spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cityManager}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate.ddl-auto: update